apiVersion: v2
name: p4pa-cie
description: P4PA CIE
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 8.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
