apiVersion: v2
name: pagopa-arc-be
description: pagopa-arc-be
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 7.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
